doctrine:
    dbal:
        driver: pdo_mysql
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        types:
            activity_type_enum: 'Titanbot\Daemon\Infrastructure\Persistence\Doctrine\Type\ActivityType'
            gender_enum: 'Titanbot\Daemon\Infrastructure\Persistence\Doctrine\Type\GenderType'

    orm:
        mappings:
            Titanbot.Entity:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Resources/doctrine/mapping'
                prefix: 'Titanbot\Daemon\Domain\Entity'
                alias: Titanbot.Entity
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
