nelmio_api_doc:
    documentation:
        info:
            title: Titanbot daemon API
            description: Titanbot daemon module
            version: 1.0.0
    models:
        use_jms: false
        names: true
