framework:
    validation:
        mapping:
            paths:
                - '%kernel.project_dir%/src/Infrastructure/Validator'

when@test:
    framework:
        validation:
            not_compromised_password: false
